# Descripción

En este archivo se hará un análisis exploratorio el dataset maestro que contiene los datos históricos de los 12 meses de operaciones del último año de la empresa cyclistic.

El objetivo de este EDA es diagnostico ya que la intención es visualizar el estado actual del dataset y poder tomar desiciones al respecto y asegurar los siguientes aspectos:

- Relevantes → sirven para responder la pregunta

- Íntegros → no faltan partes críticas

- Consistentes → no se contradicen

- Correctos → tienen sentido lógico

- Confiables → puedes defenderlos ante otros

In [1]:
import pandas as pd

df=pd.read_csv('dataset_maestro_ciclistas.csv')
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [2]:
df.shape

(5552994, 13)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5552994 entries, 0 to 5552993
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 550.8+ MB

In [4]:
df.describe()

          start_lat     start_lng       end_lat       end_lng
count  5.552994e+06  5.552994e+06  5.547459e+06  5.547459e+06
mean   4.190366e+01 -8.764648e+01  4.190411e+01 -8.764683e+01
std    4.443323e-02  2.726130e-02  4.460469e-02  2.746640e-02
min    4.164850e+01 -8.789000e+01  4.149000e+01 -8.810000e+01
25%    4.188213e+01 -8.766000e+01  4.188241e+01 -8.766000e+01
50%    4.189859e+01 -8.764177e+01  4.189964e+01 -8.764275e+01
75%    4.193000e+01 -8.762991e+01  4.193000e+01 -8.763000e+01
max    4.207000e+01 -8.752000e+01  4.221000e+01 -8.742000e+01

In [5]:
df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [6]:
df.isna().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1184673
start_station_id      1184673
end_station_name      1243305
end_station_id        1243305
start_lat                   0
start_lng                   0
end_lat                  5535
end_lng                  5535
member_casual               0
dtype: int64

In [7]:
df.isna().sum().sort_values(ascending=False)

end_station_name      1243305
end_station_id        1243305
start_station_id      1184673
start_station_name    1184673
end_lat                  5535
end_lng                  5535
started_at                  0
rideable_type               0
ride_id                     0
ended_at                    0
start_lat                   0
start_lng                   0
member_casual               0
dtype: int64

NOTA: Aun no se que columnas usare para mi analisis, pero al primer vistazo pense que quiza el nombre de la estacion seria util, pero resulta que hay muchos datos nulos. Supuestamente la latitud y longitud son un tipo de dato que indica ubicacion también, sera que me seran utiles esos datos?, sera que en caso de que los vaya a usar puedo cruzar la informacion de la latitud para rellenar los datos que faltan en el nombre de las estaciones?

Tambien tengo la duda sobre si deberia combinar la informacion de dos columnas para hacerla una sola. Lo analizaré después

In [8]:
df.nunique()

ride_id               5552994
rideable_type               2
started_at            5551938
ended_at              5550528
start_station_name       1893
start_station_id         3360
end_station_name         1901
end_station_id           3383
start_lat              118725
start_lng              116911
end_lat                  2030
end_lng                  2028
member_casual               2
dtype: int64

In [9]:
df.nunique().sort_values(ascending=True)

rideable_type               2
member_casual               2
start_station_name       1893
end_station_name         1901
end_lng                  2028
end_lat                  2030
start_station_id         3360
end_station_id           3383
start_lng              116911
start_lat              118725
ended_at              5550528
started_at            5551938
ride_id               5552994
dtype: int64

In [10]:
df['rideable_type'].value_counts()

rideable_type
electric_bike    3604953
classic_bike     1948041
Name: count, dtype: int64

In [11]:
df['member_casual'].value_counts()

member_casual
member    3553497
casual    1999497
Name: count, dtype: int64

Hasta este punto he hecho un EDA general de mi data set. He revisado forma, tipos de datos, valores nulos, unicos, y total de datos. Con esto hecho ahora voy a profundizar más sobre cada columna y asi poder determinar que acción tomar al respecto: eliminar, limpiar, dejarla o combinarlas. Con esto podre dejar las columnas que realmente me sirven.

Para esto empezare a analizar las columnas por orden de dependencia:

1. Nivel 1: Las "Columnas Identidad" (IDs)
Por qué primero: Porque si el ride_id está duplicado, no tiene sentido limpiar lo demás; primero debes resolver por qué hay basura repetida.

2. Nivel 2: Las "Columnas de Tiempo" (Fechas)
Por qué segundo: Porque las fechas son el corazón de este proyecto. Necesitas convertirlas a formato datetime antes de poder calcular nada más Estandarización de formato.

3. Nivel 3: Columnas Calculadas (Ingeniería de datos)
Por qué aquí: Una vez que las fechas están limpias, creas ride_length y day_of_week. Estas nuevas columnas te van a revelar Outliers (viajes de 0 segundos o de 1 mes) que antes no podías ver.

4. Nivel 4: Columnas Categóricas (Bicicletas y Usuarios)
Qué haces: Revisas rideable_type y member_casual.

5. Nivel 5: Columnas Geográficas y de Estación (Las más pesadas)
Por qué al final: Las columnas start_station_name, lat, lng, etc., suelen tener muchos nulos.

## Nivel 1: Columna de identidad [ride_id]

Este dato representa unicidad en este data set, debe ser único e irrepetible ya que cada uno indica el registro de cada viaje.

In [ ]:
# Número de identificadores únicos de viaje

df['ride_id'].nunique()

5552994

In [ ]:
# Longitud de los identificadores de viaje

df['ride_id'].astype('str').str.len().value_counts()

ride_id
16    5552994
Name: count, dtype: int64

In [ ]:
# Tipos de datos en la columna 'ride_id'

df['ride_id'].apply(type).value_counts()

ride_id
<class 'str'>    5552994
Name: count, dtype: int64

In [ ]:
# Tipos de datos en la columna 'ride_id'

df['ride_id'].dtype

dtype('O')

In [ ]:
# Inspección visual de los primeros 15 valores en 'ride_id'

df['ride_id'].head(15)

0     7569BC890583FCD7
1     013609308856B7FC
2     EACACD3CE0607C0D
3     EAA2485BA64710D3
4     7F8BE2471C7F746B
5     0B8DD16A9B77A1C7
6     65DD88D2EA5AA24A
7     EAC4EE361C030130
8     46267A54446162B5
9     B5D4F9782121EA51
10    3C1E48C025E88653
11    B157E60BBF2BA5F6
12    81AE62C30F86C0D2
13    4978AFB4F96F17A6
14    1DCC4C0315A3B282
Name: ride_id, dtype: object

In [ ]:
# Detección de posibles problemas en 'ride_id'

ide=df['ride_id'].astype('string')

extremos=ide != ide.str.strip() # espacios al inicio o final
medio=ide.str.contains(r"\S\s+\S", regex=True, na=False) # espacios en el medio
tabs=ide.str.contains(r"[\t\n\r]", regex=True, na=False) # tabulaciones o saltos de línea
caracteres_especiales=ide.str.contains(r"[^\w-]", regex=True, na=False) # caracteres no alfanuméricos ni guiones

extremos.sum(), medio.sum(), tabs.sum(), caracteres_especiales.sum()

(np.int64(0), np.int64(0), np.int64(0), np.int64(0))

## Nivel 1 completo

En el EDA del nivel 1 se encontro que la columna de ID esta limpia:

 - Sin nulos

 - Sin duplicados

 - Misma longitud

 - Sin espacios (bordes/medio)

 - Sin tabs / saltos invisibles

 - Sin caracteres especiales raros