# Descripción

En este archivo se hará un análisis exploratorio el dataset maestro que contiene los datos históricos de los 12 meses de operaciones del último año de la empresa cyclistic.

El objetivo de este EDA es diagnostico ya que la intención es visualizar el estado actual del dataset, poder tomar desiciones al respecto y asegurar los siguientes aspectos:

- Relevantes → sirven para responder la pregunta

- Íntegros → no faltan partes críticas

- Consistentes → no se contradicen

- Correctos → tienen sentido lógico

- Confiables → puedes defenderlos ante otros

In [1]:
import pandas as pd

df=pd.read_csv('dataset_maestro_ciclistas.csv')
df.head(10)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
5,0B8DD16A9B77A1C7,electric_bike,2025-01-02 16:09:06.825,2025-01-02 16:10:55.784,Halsted St & 21st St,13162,Halsted St & 18th St,13099,41.853780,-87.646603,41.857506,-87.645991,member
6,65DD88D2EA5AA24A,electric_bike,2025-01-19 01:11:59.684,2025-01-19 01:15:54.187,Halsted St & Wrightwood Ave,TA1309000061,Southport Ave & Wrightwood Ave,TA1307000113,41.929143,-87.649077,41.928773,-87.663913,member
7,EAC4EE361C030130,electric_bike,2025-01-24 06:43:28.984,2025-01-24 07:01:38.943,Stave St & Armitage Ave,13266,Canal St & Madison St,13341,41.917741,-87.691392,41.882409,-87.639767,member
8,46267A54446162B5,electric_bike,2025-01-06 08:45:24.741,2025-01-06 08:50:20.458,Larrabee St & Kingsbury St,TA1306000009,Ogden Ave & Race Ave,13194,41.897764,-87.642884,41.891795,-87.658751,member
9,B5D4F9782121EA51,electric_bike,2025-01-01 16:56:36.927,2025-01-01 17:03:26.608,Albany Ave & Bloomingdale Ave,15655,Campbell Ave & Fullerton Ave,15648,41.914027,-87.705126,41.924632,-87.689307,member

In [3]:
df.shape

(5552994, 13)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5552994 entries, 0 to 5552993
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 550.8+ MB

In [2]:
df.describe()

          start_lat     start_lng       end_lat       end_lng
count  5.552994e+06  5.552994e+06  5.547459e+06  5.547459e+06
mean   4.190366e+01 -8.764648e+01  4.190411e+01 -8.764683e+01
std    4.443323e-02  2.726130e-02  4.460469e-02  2.746640e-02
min    4.164850e+01 -8.789000e+01  4.149000e+01 -8.810000e+01
25%    4.188213e+01 -8.766000e+01  4.188241e+01 -8.766000e+01
50%    4.189859e+01 -8.764177e+01  4.189964e+01 -8.764275e+01
75%    4.193000e+01 -8.762991e+01  4.193000e+01 -8.763000e+01
max    4.207000e+01 -8.752000e+01  4.221000e+01 -8.742000e+01

In [ ]:
df.dtypes

In [3]:
df.isna().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1184673
start_station_id      1184673
end_station_name      1243305
end_station_id        1243305
start_lat                   0
start_lng                   0
end_lat                  5535
end_lng                  5535
member_casual               0
dtype: int64

In [ ]:
df.isna().sum().sort_values(ascending=False)

NOTA: Aun no se que columnas usare para mi analisis, pero al primer vistazo pense que quiza el nombre de la estacion seria util, pero resulta que hay muchos datos nulos. Supuestamente la latitud y longitud son un tipo de dato que indica ubicacion también, sera que me seran utiles esos datos?, sera que en caso de que los vaya a usar puedo cruzar la informacion de la latitud para rellenar los datos que faltan en el nombre de las estaciones?

Tambien tengo la duda sobre si deberia combinar la informacion de dos columnas para hacerla una sola. Lo analizaré después

In [6]:
df.nunique()

ride_id               5552994
rideable_type               2
started_at            5551938
ended_at              5550528
start_station_name       1893
start_station_id         3360
end_station_name         1901
end_station_id           3383
start_lat              118725
start_lng              116911
end_lat                  2030
end_lng                  2028
member_casual               2
dtype: int64

In [7]:
df['rideable_type'].value_counts()

rideable_type
electric_bike    3604953
classic_bike     1948041
Name: count, dtype: int64

In [8]:
df['member_casual'].value_counts()

member_casual
member    3553497
casual    1999497
Name: count, dtype: int64

Hasta este punto he hecho un EDA general de mi data set. He revisado forma, tipos de datos, valores nulos, unicos, y total de datos. Con esto hecho ahora voy a profundizar más sobre cada columna y asi poder determinar que acción tomar al respecto: eliminar, limpiar, dejarla o combinarlas. Con esto podre dejar las columnas que realmente me sirven.

Para esto empezare a analizar las columnas por orden de dependencia:

1. Nivel 1: Las "Columnas Identidad" (IDs)
Por qué primero: Porque si el ride_id está duplicado, no tiene sentido limpiar lo demás; primero debes resolver por qué hay basura repetida.

2. Nivel 2: Las "Columnas de Tiempo" (Fechas)
Por qué segundo: Porque las fechas son el corazón de este proyecto. Necesitas convertirlas a formato datetime antes de poder calcular nada más Estandarización de formato.

3. Nivel 3: Columnas Calculadas (Ingeniería de datos)
Por qué aquí: Una vez que las fechas están limpias, creas ride_length y day_of_week. Estas nuevas columnas te van a revelar Outliers (viajes de 0 segundos o de 1 mes) que antes no podías ver.

4. Nivel 4: Columnas Categóricas (Bicicletas y Usuarios)
Qué haces: Revisas rideable_type y member_casual.

5. Nivel 5: Columnas Geográficas y de Estación (Las más pesadas)
Por qué al final: Las columnas start_station_name, lat, lng, etc., suelen tener muchos nulos.

## Nivel 1: Columna de identidad [ride_id]

Este dato representa unicidad en este data set, debe ser único e irrepetible ya que cada uno indica el registro de cada viaje.

In [9]:
# Número de identificadores únicos de viaje

df['ride_id'].nunique()

5552994

In [10]:
# Longitud de los identificadores de viaje

df['ride_id'].astype('str').str.len().value_counts()

ride_id
16    5552994
Name: count, dtype: int64

In [11]:
# Tipos de datos en la columna 'ride_id'

df['ride_id'].apply(type).value_counts()

ride_id
<class 'str'>    5552994
Name: count, dtype: int64

In [12]:
# Tipos de datos en la columna 'ride_id'

df['ride_id'].dtype

dtype('O')

In [14]:
# Inspección visual de los primeros 15 valores en 'ride_id'

df['ride_id'].head(15)

0     7569BC890583FCD7
1     013609308856B7FC
2     EACACD3CE0607C0D
3     EAA2485BA64710D3
4     7F8BE2471C7F746B
5     0B8DD16A9B77A1C7
6     65DD88D2EA5AA24A
7     EAC4EE361C030130
8     46267A54446162B5
9     B5D4F9782121EA51
10    3C1E48C025E88653
11    B157E60BBF2BA5F6
12    81AE62C30F86C0D2
13    4978AFB4F96F17A6
14    1DCC4C0315A3B282
Name: ride_id, dtype: object

In [15]:
# Detección de posibles problemas en 'ride_id'

ide=df['ride_id'].astype('string')

extremos=ide != ide.str.strip() # espacios al inicio o final
medio=ide.str.contains(r"\S\s+\S", regex=True, na=False) # espacios en el medio
tabs=ide.str.contains(r"[\t\n\r]", regex=True, na=False) # tabulaciones o saltos de línea
caracteres_especiales=ide.str.contains(r"[^\w-]", regex=True, na=False) # caracteres no alfanuméricos ni guiones

extremos.sum(), medio.sum(), tabs.sum(), caracteres_especiales.sum()

(0, 0, 0, 0)

## Nivel 1 completo

En el EDA del nivel 1 se encontro que la columna de ID esta limpia:

 - Sin nulos

 - Sin duplicados

 - Misma longitud

 - Sin espacios (bordes/medio)

 - Sin tabs / saltos invisibles

 - Sin caracteres especiales raros

## Nivel 2: Fechas 

Las fechas aportan un valor analítico muy importante porque revelan tendencias, estacionalidad y cohortes, sin embargo, suelen ser los datos más problemas en su formato.

Para este data set tenemos started_at y ended_at y haremos el EDA en tres momentos

- Data Profiling (Validación estructural de fechas): formato consistente, longitud, rango, nulos, duplicados esperables
- Type Casting Conversión técnica de String a Datetime64.
- Business Rules Validation (Coherencia temporal): inicio ≤ fin, duración válida, detección de outliers

In [16]:
df[['started_at','ended_at']].head(10)

                started_at                 ended_at
0  2025-01-21 17:23:54.538  2025-01-21 17:37:52.015
1  2025-01-11 15:44:06.795  2025-01-11 15:49:11.139
2  2025-01-02 15:16:27.730  2025-01-02 15:28:03.230
3  2025-01-23 08:49:05.814  2025-01-23 08:52:40.047
4  2025-01-16 08:38:32.338  2025-01-16 08:41:06.767
5  2025-01-02 16:09:06.825  2025-01-02 16:10:55.784
6  2025-01-19 01:11:59.684  2025-01-19 01:15:54.187
7  2025-01-24 06:43:28.984  2025-01-24 07:01:38.943
8  2025-01-06 08:45:24.741  2025-01-06 08:50:20.458
9  2025-01-01 16:56:36.927  2025-01-01 17:03:26.608

In [17]:
df['ended_at'].apply(type).value_counts()
df['started_at'].apply(type).value_counts()

started_at
<class 'str'>    5552994
Name: count, dtype: int64

In [18]:
#Longitud de los valores en 'started_at' y 'ended_at'

df['started_at'].astype('str').str.len().value_counts()
df['ended_at'].astype('str').str.len().value_counts()

ended_at
23    5552994
Name: count, dtype: int64

In [19]:
# Inspección visual de los separadores únicos en 'started_at' y 'ended_at' 

print(df['started_at'].replace(r'\d',' ', regex=True).unique())
print(df['ended_at'].replace(r'\d',' ', regex=True).unique())

['    -  -     :  :  .   ']
['    -  -     :  :  .   ']

In [20]:
print(df[['started_at','ended_at']].max())
print(df[['started_at','ended_at']].min())

started_at    2025-12-31 23:53:24.274
ended_at      2025-12-31 23:58:42.046
dtype: object
started_at    2024-12-31 18:54:41.803
ended_at      2025-01-01 00:00:01.447
dtype: object

In [21]:
partes_fecha=df['started_at'].str.split('-|:| ', expand=True)
partes_fecha.head()

      0   1   2   3   4       5
0  2025  01  21  17  23  54.538
1  2025  01  11  15  44  06.795
2  2025  01  02  15  16  27.730
3  2025  01  23  08  49  05.814
4  2025  01  16  08  38  32.338

In [ ]:
# Extracción de año, mes y día de 'started_at' para saber que valores únicos hay

'''partes_fecha_s=df['started_at'].str.split('-|:| ', expand=True)
año_s=partes_fecha_s[0].unique()
mes_s=partes_fecha_s[1].unique()
dia_s=sorted(partes_fecha_s[2].unique())

año_s, mes_s, dia_s'''

In [ ]:
# Extracción de año, mes y día de 'ended_at' para saber que valores únicos hay

'''partes_fecha_e=df['ended_at'].str.split('-|:| ', expand=True)
año_e=partes_fecha_e[0].unique()
mes_e=partes_fecha_e[1].unique()
dia_e=sorted(partes_fecha_e[2].unique())

año_e, mes_e, dia_e'''

In [ ]:
'''partes_hora_s=df['started_at'].str.split('-|:| ', expand=True)
hora=sorted(partes_hora_s[3].unique())
minuto=sorted(partes_hora_s[4].unique())
segundo=sorted(partes_hora_s[5].unique())
hora, minuto, segundo'''

In [ ]:
'''partes_hora_e=df['ended_at'].str.split('-|:| ', expand=True)
hora=sorted(partes_hora_e[3].unique())
minuto=sorted(partes_hora_e[4].unique())
segundo=sorted(partes_hora_e[5].unique())
hora, minuto, segundo'''

In [22]:
df['started_at'].isna().sum()
df['ended_at'].isna().sum()

0

In [23]:
#Revisamos duplicados, aunque es logico que existan duplicados en fechas de inicio y fin de viajes, pero sin que la cifra sea exagerada
#Además estos duplicados se conservan ya que los identificadores de viaje son únicos, entonces no afectan la unicidad del registro.

duplicados_s=df['started_at'].duplicated().sum()
duplicados_e=df['ended_at'].duplicated().sum()

duplicados_s, duplicados_e

(1056, 2466)

### Data profiling completo

Se verificó que no hay nulos, las fechas tienen longitud y formato coherente para todos los registros de started_at y ended_at, hay duplicados válidos.

In [ ]:
# Convertir fechas a formato datetime

df['started_at']=pd.to_datetime(df['started_at'], errors='coerce')
df['ended_at']=pd.to_datetime(df['ended_at'], errors='coerce')

In [ ]:
df[['started_at','ended_at']].head()

In [ ]:
df[['started_at','ended_at']].dtypes

In [ ]:
df['started_at'].isna().sum()
df['ended_at'].isna().sum()

In [ ]:
df[['started_at','ended_at']].shape

### Type Casting Completo

Las fechas fueron convertidas de string a datetime64[ns]. Además se hizo una validación rapida, confirmando nuevamente que no hay nulos, y las filas estan completas.

aspectos a revisar duracion del viaje: que dure  un tiempo logico, no -4 minutos o 00 minutos. Duraciones extremas: minimo y maximo de fechas. Media mediana y moda

In [ ]:
#Orden temporal de las fechas

orden_invalido=df['started_at'] > df['ended_at']
print(orden_invalido.sum())
df[orden_invalido].head()

In [ ]:
df['duration_min']=(df['ended_at'] - df['started_at']).dt.total_seconds() / 60
tiempo_negativo= df['duration_min']<0
print(tiempo_negativo.sum())    
tiempo_negativo.value_counts()

In [ ]:
tiempo_cero= df['duration_min']==0
print(tiempo_cero.sum())

In [ ]:
df['duration_min'].max()

In [ ]:
df['duration_min'].mean()

In [ ]:
df['duration_min'].describe(percentiles=[0.01,0.05,0.1,0.25,0.5,0.75,0.9,0.95,0.99])
#Estoy analizando los percentiles para entender mejor la distribución de la duración de los viajes y detectar posibles valores atípicos.
#Definitivamente un valor de 26 horas es atipico ya que incluso el 99% de los viajes duran menos o igual a (1h 8min-89.03 min).

In [ ]:
#Inspeccionde outliers en la duración de los viajes
outlier_2h=(df['duration_min']>2*60).sum()
outlier_6h=(df['duration_min']>6*60).sum()      
outlier_12h=(df['duration_min']>12*60).sum()
outlier_24h=(df['duration_min']>24*60).sum()

print('Outlier mayor a dos horas: ', outlier_2h)
print('Outlier mayor a seis horas: ', outlier_6h)           
print('Outlier mayor a doce horas: ', outlier_12h)
print('Outlier mayor a veinticuatro horas: ', outlier_24h)

In [ ]:
# Inspección de los outliers en la duración de los viajes, Se crean columnas booleanas para identificar los outliers

df["outlier_2h"]=(df['duration_min']>2*60)
df["outlier_6h"]=(df['duration_min']>6*60)
df["outlier_12h"]=(df['duration_min']>12*60)       
df["outlier_24h"]=(df['duration_min']>24*60)
print('Outlier mayor a dos horas: ', df["outlier_2h"])
print('Outlier mayor a seis horas: ', df["outlier_6h"])
print('Outlier mayor a doce horas: ', df["outlier_12h"])
print('Outlier mayor a veinticuatro horas: ', df["outlier_24h"])

In [ ]:
# Fechas fuera del rango esperado
print("Fechas maximas de started_at y ended_at: ", df['started_at'].max(), df['ended_at'].max())
print("Fechas minimas de started_at y ended_at: ", df['started_at'].min(), df['ended_at'].min())

In [ ]:
# Relación entre duración del viaje y tipo de usuario
outlier_2h = df.groupby("member_casual")["outlier_2h"].mean()*100
outlier_6h = df.groupby("member_casual")["outlier_6h"].mean()*100
outlier_12h = df.groupby("member_casual")["outlier_12h"].mean()*100
outlier_24h = df.groupby("member_casual")["outlier_24h"].mean()*100

outlier_2h, outlier_6h, outlier_12h, outlier_24h

In [ ]:
# Relacion entre duración del viaje y tipo de bicicleta

print(df.groupby('rideable_type')['outlier_2h'].mean()*100)
print(df.groupby('rideable_type')['outlier_6h'].mean()*100)
print(df.groupby('rideable_type')['outlier_12h'].mean()*100)
print(df.groupby('rideable_type')['outlier_24h'].mean()*100)

Se encontro lo siguiente: 29 registros que no tienen un orden valido, es decir, la hora de inicio de ruta es mayor a la hora de finalización, por lo tanto eso genera que hayan 29 duraciones negativas, no hay duraciones en 0, el promedio de viajes son 16 minutos, el 99% de los datos estan dentro del tiempo estimado de 1 h 8 minutos. El tiempo maximo de un viaje es de 26 horas y existen outliers de 2 horas en adelante. Al hacer la relacion con el tipo de bicicleta y el tipo de usuario se encontro que los outliers se encuentran especialmente en miembros casuales y bicicletas clasicas. Es necesario decidir qué hacer al respecto, cómo limpiarlos


 (Duda: osea una vez que limpie estos archivos ya no apareceran los datos sucios, sera que es buena practica dejar los datos sucios en una variable, con fines de trazabilidad, o no? porque igual eso consume recursos, En el mundo real que es lo que sucede o cuales son las buenas practicas)

### Business Rules Validation Completo

La revisión que se hizo en este paso incluye: started_at y ended_at convertidas a datetime, No nulos en fechas, Rango de fechas coherente (min/max), Regla lógica: ended_at >= started_at, Duración no negativa, Duración no extrema (outliers)

Se encontró lo siguiente:

- 29 registros con orden temporal invertido → duración negativa

- Duración máxima: 26 horas

- Los outliers se concentran en miembros casuales y bicicletas clasicas:

2h: 31,547

6h: 9,799

12h: 7,824

24h: 5,585

In [ ]:
# se crean variables con los datos limpios de duración del viaje
# esto con el fin de evaluar cómo se afectarás las metricas con y sin outliers

tiempo_valido= df[df['duration_min']>=0]
tiempo_valido.shape
tiempo_valido

In [ ]:
# Se inspecciona los datos con duracion negativa

tiempo_invalido=df[df['duration_min']<0]
tiempo_invalido.shape
tiempo_invalido

In [ ]:
#tiempo_invalido.to_csv('tiempo_invalido.csv', index=False)---- Guardar los registros con duración negativa en un archivo CSV
tiempo_invalido.shape

In [ ]:
df = df[df["duration_min"] >= 0]
df.head()

In [ ]:
df.shape

Se eliminan los 29 datos que tienen orden temporal invertido ya que  29[tiempo negativo]/5552994 [total registros]= 0.00052%. 
Según las prácticas de limpieza en análisis de datos <0.1% pueden ser considerados ruido técnico y pueden ser eliminados sin tener impacto. Dado que estos registros representan eventos inválidos desde el punto de vista del negocio, fueron excluidos del dataset analítico. Las columnas temporales se conservaron, y la variable duration_min se utiliza como métrica derivada validada.